### PR TITLE
blog content width and header image height reduced 

### PR DESCRIPTION
**Pull request by topazahmed**
image

image

### CODE REVIEW

**Comment by jeanfrancoislarente** [comment]
Hey @topazahmed - looks like the image is gone from the blog post page.

I like the new layout of the related repos under the author though

**Comment by topazahmed** [comment]
Interesting... The picture is loading on a refresh but not when going to the page on the first visit. Maybe the value is not set properly when I am setting the bg. Will look into it.
But you can see from my screenshot it's there but that was from my local machine.

**Comment by topazahmed** [comment]
Updated this with narrow content and new layout... 
Let give it a merge if looks good

**Comment by topazahmed** [comment]
https://sitecore-demo-blog-pdabjw3k7.vercel.app/posts/xgenerator-intro

If this ok, please merge

**Pull request merged**
